name: Results Processor
on: 
  workflow_dispatch:
   
jobs:
  job1:
    name: Deploy Results Processor Application
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - id: step1
      name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - id: step2
      name: Build Ioannina
      run: dotnet build YellowSubmarineResultsProcessor/YellowSubmarineResultsProcessor.csproj --configuration Debug

    - id: step3
      name: Publish Ioannina
      run: dotnet publish YellowSubmarineResultsProcessor/YellowSubmarineResultsProcessor.csproj -c Debug -o ${{env.DOTNET_ROOT}}/YellowSubmarineResultsProcessor-app 

    - id: step4
      name: 'Deploy Ioannina to Function App'
      uses: Azure/functions-action@v1.1.6
      with:
        app-name: YellowSubmarineResultsProcessor-func
        package: ${{env.DOTNET_ROOT}}/YellowSubmarineResultsProcessor-app 
